name: Create EKS & BastionHost

on:
  workflow_dispatch:

jobs:
  eks:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz
          sudo mv eksctl /usr/local/bin

      - name: Create Cluster
        run: eksctl create cluster --name demo-cluster --region us-west-2 --managed

      - name: Map Bastion IAM Role
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

          eksctl create iamidentitymapping \
            --cluster demo-cluster \
            --arn arn:aws:iam::$ACCOUNT_ID:role/bastion-eks-role \
            --group system:masters \
            --username ec2-user
            
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      # STEP 3: Deploy Bastion via Terraform
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
