name: Create EKS (Sandbox)

on:
  workflow_dispatch:

jobs:
  eks:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-west-2

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz
          sudo mv eksctl /usr/local/bin

      - name: Create Cluster
        run: eksctl create cluster --name demo-cluster --region us-west-2 --managed
